In [ ]:
'''ARRAY MANIPULATION:-
COMBINING DATASETS.
SPLITING DATA FOR TRAINING.
MODIFYING ARRAY STRUCTURE.
ADDING OR REMOVING 
MANAGING MEMORY.

In [9]:
'''CONCATINATION OF ARRAY:-(ONLY WORK TO JUST JOIN TWO STRING TOGETHER)
ADDITION OF ARRAY:-'''
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.array([[9,10],[11,12]])
print(np.concatenate((a,b,c)),'\n')        # ARRAY MUST HAVE SAME SHAPE TO WORK CONCATENATE.
print('AXIS 0:- \n',np.concatenate((a,b,c),axis=0),'\n')       # AXIS=0 JOINS ROWS.
print('AXIS-1:-\n',np.concatenate((a,b,c),axis=1))       # EXIS=1 MEANS JOIN COLUMNS.

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

AXIS 0:- 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

AXIS-1:-
 [[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [23]:
# STAKING FUNCTION:-(HSTACK,DSTACK)
#HSTACK:-INCREASE COLUMNS
arr1=np.array([[1,2,3],
            [4,5,6]])
arr2=np.array([[7,8,9],
            [10,11,12]])
print('HSTACK:-',np.hstack((arr1,arr2)),'\n')   # INCREASE HORIZENTAL(COLUMN). LIKE AXIS-1
print('VSTACK :-',np.vstack((arr1,arr2)),'\n')   #INCREASE VERTICAL(ROWS). LIKE AXIS-0
print('DSTACK :-',np.dstack((arr1,arr2)))   # INCREASE depth.
'''hstack → horizontal → left-right
vstack → vertical → up-down
dstack → front-back (depth)'''

HSTACK:- [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] 

VSTACK :- [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

DSTACK :- [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


'hstack → horizontal → left-right\nvstack → vertical → up-down\ndstack → front-back (depth)'

In [ ]:
'''SPLITTING ARRAYS:-
NP.SPLIT()
-SPLIT ARRAY INTO TWO EQUAL PARTS.
SYNTAX:-
NP.SPLIT(ARR,SECTION,AXIS=0)'''

In [24]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

result = np.split(arr, 3)   # HERE WE HAVE TO GIVE 3==PARTS.

print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
'''NP.ARRAY_SPLIT():-
ALLOWS UNEQUAL SPLITTING.'''

In [25]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
result=np.array_split(arr,4)    # that np.split will give error.
print(result)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
'''INSERT, APPEND, DELETE:-
NP.INSERT(ARR,INDEX,VALUES,AXIS=NONE)
NP.APPEND(ARR,VALUES,AXIS=NONE)
NP.DELETE(ARR,INDEX,AXIS=NONE)'''

In [31]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(np.insert(arr,0,7))
print(np.append(arr,(7,8,9,10)))
print(np.delete(arr,3))
print(arr)   # it means this all 3 works on copy of original anddon't affect the original.

[7 1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 5 6]
[1 2 3 4 5 6]


In [ ]:
'''COPY VS VIEW:-
View → shares original data.VIEW DOESN'T CREATE A NEW MEMORY.IF YOU CHANGE THE VIEW ORIGINAL ARRAY WILL ALSO CHANGE.
Copy → creates completely new data.

In [35]:
import numpy as np

arr = np.array([1,2,3,4])
v=arr.view()
print(v)
v[0]=100   # added 100 in place of 1
print(v)   # now view has been changed
print(arr)  # due to this original has also been changed.

[1 2 3 4]
[100   2   3   4]
[100   2   3   4]


In [37]:
import numpy as np

arr = np.array([1,2,3,4])
c=arr.copy()
c[0]=100   # added 100 in place of 1
print(c)   # chnaged copy of arr
print(arr)  # original array will not be affected.

[100   2   3   4]
[1 2 3 4]


In [39]:
'''Create an array from 1 to 15. 
Split it into 5 equal parts. '''
import numpy as np

arr=np.arange(1,16)
print('ORIGINAL ARRAY :-',arr)
print(np.split(arr,5))

ORIGINAL ARRAY :- [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15])]


In [40]:
'''Create an array from 1 to 11. 
Split it into 4 parts using array_split(). '''
import numpy as np

arr=np.arange(1,12)
print('ORIGINAL ARRAY :-',np.array_split(arr,4))

ORIGINAL ARRAY :- [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11])]


In [41]:
'''Given: arr = np.array([10, 20, 30, 40, 50]) 
Insert 25 at index 2. '''
import numpy as np

arr=np.array([10, 20, 30, 40, 50])
print(np.insert(arr,2,25))

[10 20 25 30 40 50]


In [48]:
'''Given: arr = np.array([[1,2], [3,4]]) 
Insert a new row [5,6] at index 1. '''
import numpy as np

arr=np.array([[1,2], [3,4]])
print(np.insert(arr,1,[5,6], axis=0))

[[1 2]
 [5 6]
 [3 4]]


In [49]:
'''Given: arr = np.array([5, 10, 15]) 
Append 20 and 25 at the end. '''
import numpy as np

arr=np.array([5, 10, 15])
print(np.append(arr,(20,25)))

[ 5 10 15 20 25]


In [56]:
'''Given: arr = np.array([[1,2], [3,4]]) 
Append column [7,8] to this array. '''
import numpy as np

arr=np.array([[1,2], [3,4]])
print(np.append(arr,[[7],[8]],axis=1))   # here column is told to append so axis=1,for row axis=0 is used.

[[1 2 7]
 [3 4 8]]


In [59]:
'''Given: arr = np.array([100, 200, 300, 400, 500]) 
Delete: a) Element at index 3 
b) First two elements.'''
import numpy as np

arr=np.array([100, 200, 300, 400, 500])
print(np.delete(arr,3))
print(np.delete(arr,[0,1]))

[100 200 300 500]
[300 400 500]


In [60]:
'''Given: arr = np.array([[1,2], [3,4], [5,6]]) 
Delete the second row'''
import numpy as np

arr=np.array([[1,2], [3,4], [5,6]])
print(np.delete(arr,[1],axis=0))

[[1 2]
 [5 6]]


In [63]:
'''Create: arr = np.array([1,2,3,4]) 
Create: 
view_arr using view() 
copy_arr using copy() 
Modify arr[0] = 999 
Print all three arrays. Explain what happened.'''
import numpy as np

arr=np.array([1,2,3,4])    # this is original array
print(arr)
view_arr=arr.view()     # we created view
view_arr[0]=999         # we changed in view
copy_arr=arr.copy()     # we created copy
copy_arr[0]=777         # we changed in copy
print(view_arr)        # printing view
print(copy_arr)        #printing copy
print(arr)           # original array will be changed bcz view modify original array also.copy do not modify original array.

[1 2 3 4]
[999   2   3   4]
[777   2   3   4]
[999   2   3   4]


In [70]:
'''Create array from 1 to 6. Reshape it into 2×3 matrix. Change element at position (0,1) to 100'''
arr=np.arange(1,7)
print(arr)
arr2=np.reshape(arr,(2,3))
print(arr2)
arr2[0,1]=100    # when told to change or replace use indexing only not insert==keep old then insert new.
print(arr2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[  1 100   3]
 [  4   5   6]]


In [80]:
'''Given: arr = np.array([[1,2,3], [4,5,6]]) 
Apply: 
flatten() ravel() 
Modify first element of both results. Observe difference'''
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])

a=arr.ravel()   # ravel changed the original array like view
a[0]=100
print(a)
b=arr.flatten()   # flatten do changes in copy of original array and not the original array itself.like a copy.
b[0]=100
print(b)
print(arr)

[100   2   3   4   5   6]
[100   2   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


In [94]:
'''Create array from 1 to 12. Split into 3 equal parts. Delete last element from each part. Combine all remaining elements into a single array.'''
arr=np.arange(1,13)
print(arr)
b=np.split(arr,3)
print(b)
c=[np.delete(i,-1)for i in b]
print(c)
d=np.concatenate(c)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
[array([1, 2, 3]), array([5, 6, 7]), array([ 9, 10, 11])]
[ 1  2  3  5  6  7  9 10 11]


In [110]:
'''Create a 4×4 matrix using np.arange(1,17)
• Extract the second row. 
• Extract the last column. 
• Compute the mean of the entire matrix'''
import numpy as np

arr=np.arange(1,17)
print(arr)
a=arr.reshape(4,4)
print(a)
print(a[1])
print(a[0:4,3:4])
print(a[:,3])   # [row,column] as we want all row so : and column only 3rd so.
print(np.mean(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[5 6 7 8]
[[ 4]
 [ 8]
 [12]
 [16]]
[ 4  8 12 16]
8.5


In [120]:
'''Create array: arr = [5, 10, 15, 20, 25, 30] 
• Extract elements greater than 10 AND less than 30. 
• Find their cumulative sum.'''

import numpy as np

arr=np.array([5, 10, 15, 20, 25, 30])
ext=arr[(10<arr) & (arr<30)]
print("ALL ELEMENTS GREATER THAN 10 AND LESS THAN 30 :---",ext)
print(np.cumsum(ext))                # cumsum is running total.


'''
| For normal Python | For NumPy |
| ----------------- | --------- |
| `and`             | `&`       |
| `or`              | `\|`      |'''

ALL ELEMENTS GREATER THAN 10 AND LESS THAN 30 :--- [15 20 25]
[15 35 60]


<>:17: SyntaxWarning: "\|" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\|"? A raw string is also an option.
<>:17: SyntaxWarning: "\|" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\|"? A raw string is also an option.
C:\Users\Rdvel\AppData\Local\Temp\ipykernel_16024\1304533881.py:17: SyntaxWarning: "\|" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\|"? A raw string is also an option.
  | `or`              | `\|`      |'''


'\n| For normal Python | For NumPy |\n| ----------------- | --------- |\n| `and`             | `&`       |\n| `or`              | `\\|`      |'

In [132]:
'''Generate 10 random integers between 1 and 50. 
• Sort them. 
• Return indices that would sort the original array. Find the 75th percentile.'''
import numpy as np
arr=np.random.randint(1,50,10)
print(arr)
print(np.argsort(arr))
arr.sort()
print(arr)
print(np.argsort(arr))
print(np.percentile(arr,75))

[15 36 21  9 48 43 41  8 27 29]
[7 3 0 2 8 9 1 6 5 4]
[ 8  9 15 21 27 29 36 41 43 48]
[0 1 2 3 4 5 6 7 8 9]
39.75


In [152]:
'''Create two 2x3 matrices.
• Concatenate them row-wise. 
• Then split the result into 2 equal parts. '''
arr=np.arange(22,28)
a=arr.reshape(2,3)
print(a)
arr2=np.arange(100,106)
b=arr2.reshape(2,3)
print(b)
c=np.concatenate((a,b),axis=0)
print(c)
print(np.split(c,2))

[[22 23 24]
 [25 26 27]]
[[100 101 102]
 [103 104 105]]
[[ 22  23  24]
 [ 25  26  27]
 [100 101 102]
 [103 104 105]]
[array([[22, 23, 24],
       [25, 26, 27]]), array([[100, 101, 102],
       [103, 104, 105]])]


In [157]:
'''Create array: arr = [1, 2, 2, 3, 4, 4,5] 
• Remove duplicate values. 
• Reverse the array using slicing. 
Compute standard deviation.'''
arr=np.array([1, 2, 2, 3, 4, 4,5])
a=np.unique(arr)
print(a)
b=a[::-1]
print(b)
print(np.std(b))

[1 2 3 4 5]
[5 4 3 2 1]
1.4142135623730951


In [169]:
'''Create a 5×5 matrix using np.arange(1,26). 
• Extract all elements greater than 10 and less than 20.
Replace those values with O using boolean indexing.
Compute total sum of modified matrix.'''
import numpy as np

arr=np.arange(1,26)
print(arr,'\n')
a=arr.reshape(5,5)
print(a)
elm=a[(10<a) & (a<20)]
print('ALL ELEMENTS GREATER THAN 10 AND LESS THAN 20 :-',elm)
a[(10<a) & (a<20)]=0
print(a)
b=a
print(np.sum(b))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
ALL ELEMENTS GREATER THAN 10 AND LESS THAN 20 :- [11 12 13 14 15 16 17 18 19]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [ 0  0  0  0 20]
 [21 22 23 24 25]]
190


In [178]:
'''Generate 1000 random numbers from normal distribution.
Compute mean and standard deviation.  
Clip values between -1 and 1. 
Count how many values were clipped.'''
import numpy as np

arr=np.random.randn(1000)
print(arr)
print(np.mean(arr))
print(np.std(arr))
b=np.clip(arr,-1,1)    # cliping means 
print(b)
count=np.sum(arr!=b)   # only check which value changed after clipping.
print(count)

[ 1.55144470e-03 -7.42837123e-01  4.89744475e-02 -1.21650622e+00
  5.74394037e-01 -1.30434596e+00  8.35920615e-01  4.14060507e-01
 -7.79877899e-02  2.67228950e-01 -3.48760960e-02  1.03639754e+00
  1.40413129e+00  1.19877695e+00  5.91595165e-01  8.66981001e-01
 -5.35104960e-01 -2.56825478e+00 -7.17331650e-01  2.36964829e-01
  2.30298833e+00  2.23001231e+00  3.17587616e-01  1.90806933e-01
  5.02095947e-01 -8.00409919e-01 -1.10589213e+00 -8.38901792e-01
  3.68153093e-01 -2.02644131e-01  2.24426613e-01 -9.10571853e-01
  3.94637179e-01  1.24081914e+00  6.47183016e-01 -1.13374701e+00
  5.23564985e-01  1.65846917e+00  8.90468908e-01  6.63819972e-01
  2.93585035e-02  1.17620760e+00 -3.55670275e-02 -6.81366630e-01
 -6.92500922e-01  1.94277173e-01 -1.43666890e+00  6.98348672e-01
 -7.61882912e-01  1.25813683e+00 -3.93933399e-01  4.09437353e-01
  1.17521492e+00 -1.99193328e+00 -1.09164554e+00 -3.03124663e+00
  1.00855456e+00 -2.01519753e+00 -3.45569657e-01 -1.29899437e+00
  5.06851565e-02 -1.79172

In [ ]:
'''
| Original | After clipping |
| -------- | -------------- |
| -5       | -1             |
| -2       | -1             |
| 0        | 0              |
| 1        | 1              |
| 4        | 1              |
| 10       | 1              |

np.clip(array, min_value, max_value)'''

In [188]:
'''Create array: arr = [10, 20, np.nan, 40, 50, np.nan]
Compute mean ignoring NaN. 
Replace NaN values with O. 
Compute new mean. '''
arr=np.array([10, 20, np.nan, 40, 50, np.nan])
print(np.nanmean(arr))    # nanmean will ignore nan values.
a=np.where(np.isnan(arr),0,arr)   #nan is never equal to anyone not even itself so never where in condition arr==np.nan use this np.isnan(arr)
print(a)
print(np.mean(a))

30.0
[10. 20.  0. 40. 50.  0.]
20.0


In [198]:
'''Create two matrices: A (3×3) using np.arange() B (3×3) random integers between 1 and 10.
Perform element-wise multiplication.
Compute 90th percentile of result. '''
arr=np.arange(1,10)
a=arr.reshape(3,3)
print(a)
b=np.random.randint(1,10,(3,3))
print(b)
c=np.multiply(a,b)
print(c)
print(np.percentile(c,90))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 9 5]
 [5 7 5]
 [1 8 5]]
[[ 5 18 15]
 [20 35 30]
 [ 7 64 45]]
48.800000000000004


In [213]:
'''Create array: arr = np.arange(1,21)
Reshape into 4x5 matrix. 
Extract elements divisible by both 2 and 3.
Insert value 999 at index 2. 
Delete last element.
Verify whether all remaining values are positive.'''
import numpy as np

arr=np.arange(1,21)
a=arr.reshape(4,5)
print(a)
b=a[(a%2==0) & (a%3==0)]
print(b)
c=np.insert(b,2,999)
print(c)
d=np.delete(c,-1)
print(d)
print(np.all(d>0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 6 12 18]
[  6  12 999  18]
[  6  12 999]
True
