In [5]:
'''Create a 1D NumPy array:
arr = [10, 20, 30, 40, 50]
Print:- First element- Last element using negative indexing'''

arr=[10,20,30,40,50]
print(arr[0],'\n',arr[-1])

10 
 50


In [7]:
'''Given array:
arr = [5, 10, 15, 20, 25, 30]
Extract elements from index 1 to 4 using slicing.'''

arr=[5,10,15,20,25,30]
print(arr[1:5])

[10, 15, 20, 25]


In [11]:
'''
Given array:
arr = [0, 2, 4, 6, 8, 10]
Extract every second element using step slicing.'''

arr=[0,2,4,6,8,10]
print(arr[::2])

[0, 4, 8]


In [14]:
'''Create a 2D array:
[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
Print the element located at:
Row 2, Column 1 (using proper indexing)'''
import numpy as np
arr=np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(arr[1,0])          # : is only for slicing and that is always forward.not like 1:0 it is not possible.

4


In [15]:
'''Using the same 2D array from Question 4,
Extract the first two rows'''
arr=np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(arr[0:2,0:4])

[[1 2 3]
 [4 5 6]]


In [16]:
'''Using the same 2D array,
Extract the submatrix:
[[2, 3],
[5, 6]'''

arr=np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(arr[0:2,1:4])

[[2 3]
 [5 6]]


In [6]:
'''Create array:
arr = [10, 20, 30, 40, 50]
Using fancy indexing, extract:- 1st element- 3rd element- 5th elemen'''
import numpy as np

arr=np.array([10,20,30,40,50])
print(arr[[0,2,4]])

[10 30 50]


In [7]:
'''Create array:
arr = [5, 10, 15, 20, 25]
Using boolean indexing, extract elements greater than 12.'''

import numpy as np
arr=np.array([5,10,15,20,25])
print(arr[arr>12])

[15 20 25]


In [10]:
'''Given array:
arr = [3, 6, 9, 12, 15]
Use np.where() to find indices where values are greater than 8'''
import numpy as np
arr=np.array([3,6,9,12,15])
print(np.where(arr>8))
a=np.where(arr>8)
print(arr[a])

(array([2, 3, 4]),)
[ 9 12 15]


In [11]:
'''Create array:
arr = [1, 2, 3, 4, 5]
Reverse the array using slicing.'''

import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [17]:
'''Create arrays:
a = [2, 4, 6]
b = [1, 2, 3]
Perform:- Element-wise multiplication
- Element-wise power (a squared)'''

a=[2,4,6]
b=[1,2,3]
print(np.multiply(a,b))
print(np.power(a,2))    # np.power(base, exponent)  --> base =a and exponent=2,3,4,5,6 (power)
print(np.power(b,2))

[ 2  8 18]
[ 4 16 36]
[1 4 9]


In [23]:
'''Create array:
arr = [4, 9, 16, 25]
Compute:- Square root- Mean- Maximum valu'''
import numpy as np
arr=np.array([4,9,16,25])
print(np.sqrt(arr))
print(np.mean(arr))
print(np.max(arr))

[2. 3. 4. 5.]
13.5
25
