In [1]:
# CREATE A NUMPY ARRAY USING NP.ARRAY() WITH ELEMENTS[5,10,15,20]:

import numpy as np
arr=np.array([5,10,15,20])
print(arr)

[ 5 10 15 20]


In [3]:
# CREATE AN ARRAY FROM 0 TO 18 WITH STEP OF 3 USING NP.ARANGE:-

arr=np.arange(1,19,3)
print(arr)

[ 1  4  7 10 13 16]


In [4]:
# CREATE 6 EVENLY SPACED NUMBERS BETWEEN 1 TO 3 USING NP.LINSPACE:-

arr=np.linspace(1,3,6)
print(arr)

[1.  1.4 1.8 2.2 2.6 3. ]


In [7]:
# CREATE A 2x4 ZERO MATRIX:-

arr=np.zeros((2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# CREATE A 3X3 MATRIX FILLED WITH ONES:-

arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# CREATE A 2X2 MATRIX OF RANDOM NUMBERS FROM UNIFORM DISTRIBUTION:-

arr=np.random.rand(2,2)
print(arr)

[[0.43207733 0.61960935]
 [0.0955971  0.08144147]]


In [3]:
# CREATE AN IDENTITY MATRIX OF SIZE 4:-
import numpy as np

arr=np.identity(4)   # always work like (4,4),(3,3) means create a rectangle only
print(arr)
arr1=np.eye(2,4)    # can be of any shape (2,4),(4,6) like this no restriction.
print(arr1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [14]:
# FIND THE SHAPE,SIZE,AND NUMBER OF DIMENSIONS OF THE FOLLOWING ARRAY:-([[1,2,3],[4,5,6]])

arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)     # DEPTH,ROW,COLUMN
print(arr.size)     # SIZE--->TOTAL ELEMENTS
print(arr.ndim)     # NDIM-->DIMENTIONS--->1D,2D,3D

(2, 3)
6
2


In [21]:
# CREATE AN ARRAY FROM 1 TO 12 AND RESHAPE IT INTO A 3X4 MATRIX:-

arr=np.arange(1,13)
print(arr)
a=arr
b=a.reshape(3,4)     # #DEPTH,ROW,COLUMN
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
# CREATE A 4X4 MATRIX USING NP.ARANGE() AND TRANSPOSE IT:-

arr=np.arange(1,17)
print(arr)
mat=arr
b=mat.reshape(4,4)         
print(b)
print(np.transpose(b))   # USED TO CONVERT ROW TO COLUMN AND COLUMN TO ROW.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [4]:
# GENERATE A 5 LOGARITHMICALLY SPACED NUMBER BETWEEN 10^1 AND 10^3:-

arr=np.logspace(1,3,3)   #start,stop,total numbers.GENERALLY IS BASE NOT GIVEN 10 IS GENERAL
print(arr)
arr2=np.logspace(1,3,3,base=2)   #HERE BASE IS 2
print(arr2)

[  10.  100. 1000.]
[2. 4. 8.]


In [35]:
#CREATE A RANDOM INTEGER MATRIX WITH OF SHAPE 3X3 WITH VALUES BETWEEN 10 AND 50:-

arr=np.random.randint(10,50,9)  # by default randint creates only 1 random number but ,9 means 9 random numbers are created.
b=arr
c=b.reshape(3,3)
print(c)

[[38 36 37]
 [49 10 45]
 [46 47 48]]


In [37]:
#CREATE 2X5 MATRIX BY RANDON.RANDN AND COMPUTE TOTAL MEMORY CONSUMED AND TOTAL SIZE :-

arr=np.random.randn(2,5)
print(arr)
print('TOTAL MEMORY',arr.nbytes)
print('TOTAL SIZE',arr.itemsize)

[[ 0.73714938 -0.68645273  1.12670702  0.38956379  1.02576796]
 [ 0.09003388 -0.91112045  2.27845792 -1.48845834  0.7553087 ]]
TOTAL MEMORY 80
TOTAL SIZE 8


In [11]:
# CREATE AN ARRAY OF 1 TO 9 AND FLATTEN IT USING RAVEL(),FLATEN IT USING FLATEN():-

arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
mat=arr
print('original mat :-',mat)
mat=arr.reshape(3,3)   # CHANGE THE ORIGINAL ARRAY AND GIVE IT SHAPE OORIGINALLY.
print('mat is reshaped:-',mat)
print('mat is given ravel:-',mat.ravel())   # ravel:-convert any array to 1d.Usually returns a view (linked to original array).DO not change original array.
print('mat is given flatten:-',mat.flatten())  #flatten:-convert any array to 1d. returns a copy (separate array).don't change original array.
print('now mat is :-',mat)

'''LIKE RESHAPE RAVEL AND FLATTEN DON'T CHANGE THE ORIGINAL ARRAY.'''

[1 2 3 4 5 6 7 8 9]
original mat :- [1 2 3 4 5 6 7 8 9]
mat is reshaped:- [[1 2 3]
 [4 5 6]
 [7 8 9]]
mat is given ravel:- [1 2 3 4 5 6 7 8 9]
mat is given flatten:- [1 2 3 4 5 6 7 8 9]
now mat is :- [[1 2 3]
 [4 5 6]
 [7 8 9]]


"LIKE RESHAPE RAVEL AND FLATTEN DON'T CHANGE THE ORIGINAL ARRAY."