In [3]:
import numpy as np

a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,12])
print('add:',a+b)
print('sub:',a-b)
print('mul:-',a*b)
print('div:-',a/b)
print('floor div:-',a//b)
print('power:-',a**b)
print('module:-',a%b)

add: [ 8 10 12 14 16 18]
sub: [-6 -6 -6 -6 -6 -6]
mul:- [ 7 16 27 40 55 72]
div:- [0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]
floor div:- [0 0 0 0 0 0]
power:- [         1        256      19683    1048576   48828125 2176782336]
module:- [1 2 3 4 5 6]


In [8]:
# COMPARISION OPERATOR:-(ALWAYS RETURN BOOLEAN OPERATION-->TRUE AND FALSE)
import numpy as np
a=np.array([5,10,15])
print('greater than 8:',a>8)  # just return boolean values
print('greater than 8:',a[a>8]) # return only true values.
print('LESS THAN than 8:',a<8)
print('LESS than 8:',a[a<8])
print('equal to 10:-',a==10)  # return boolean values.
print('EQUAL TO 10 :-',a[a==10]) #store in a-->only the true values.
print('GREATER THAN EQUAL TO 10:-',a>=10)
print('LESS THAN EQUAL TO 10:-',a<=10)
print('NOT EQUAL TO 10:-',a!=10)
print('NOT EQUAL TO 10:-',a[a!=10])
# total 6 operators

greater than 8: [False  True  True]
greater than 8: [10 15]
LESS THAN than 8: [ True False False]
LESS than 8: [5]
equal to 10:- [False  True False]
EQUAL TO 10 :- [10]
GREATER THAN EQUAL TO 10:- [False  True  True]
LESS THAN EQUAL TO 10:- [ True  True False]
NOT EQUAL TO 10:- [ True False  True]
NOT EQUAL TO 10:- [ 5 15]


In [14]:
#LOGICAL OPERATORS:-(AND,OR,NOT)
a=np.array([5,8,15,20])
cond1=a>8
cond2=a<18

print(np.logical_and(cond1,cond2))  # IF ONE IS FALSE THEN IT WILL BE FALSE
print(np.logical_or(cond1,cond2))   # IF ANY ONE IS TRUE THAN TRUE.
print(np.logical_not(np.logical_and(cond1,cond2)))  # IT REVERSE THE AND NOTHING ELSE.NOT IS ALWAYS REVERSE OF AND.

[False False  True False]
[ True  True  True  True]
[ True  True False  True]


In [26]:
# BASIC MATHEMATICAL OPERATORS:-

a=np.array([4,5,6])
b=np.array([7,8,9])
c=np.array([10,11,12])
# d=np.add(a,np.add(b,c))  # np.substract(),np.multiply(),np.divide()
#print(d)
print(a+b+c)
print('POWER A,B:-',np.power(a,np.power(c,b)))     # a^(c^b)
print('SQUARE ROOT OF A:-',np.sqrt(a))        # a**0.5 ,,TAKES ONLY ONE VALUE(a)
print('EXPONENT OF A :-',np.exp(a))            # in exp,,e is Euler’s number:-e ≈ 2.71828 so for a = 4 means --> 2.71828 **(raise to) 4.
print('LOG OF A:-',np.log(a))                 # To what power should e be raised to get a number?” where number is a=4,5,6
print('LOG 10 OF A :-',np.log10(a))           # 10 raised to what power gives this number?” number is a=4,5,6
print('ABSOLUTE VALUE FOR A :-',np.abs(a))    # ABSOLUTE MEANS Distance from 0.so negatibe becomes positive and positive ramins as it is.

[21 24 27]
POWER A,B:- [                   0 -2056051024289059707                    0]
SQUARE ROOT OF A:- [2.         2.23606798 2.44948974]
EXPONENT OF A :- [ 54.59815003 148.4131591  403.42879349]
LOG OF A:- [1.38629436 1.60943791 1.79175947]
LOG 10 OF A :- [0.60205999 0.69897    0.77815125]
ABSOLUTE VALUE FOR A :- [4 5 6]


In [27]:
#ROUNDING FUNCTION:-

'''You can remember:

round → nearest
floor → always down ↓
ceil → always up ↑'''

a=np.array([4.2,5.1,6.9])
print(np.round(a))
print(np.floor(a))
print(np.ceil(a))

[4. 5. 7.]
[4. 5. 6.]
[5. 6. 7.]


In [38]:
#STATISTICAL OPERATIONS:-
a=np.array([5,10,15,20,25,30,45,60,75,80,95])
print('MEANS :-',np.mean(a))   # sum of n / no. of n  MEANS AVERAGE
print('MEDIAN :-',np.median(a))   # middle value in given a
print('STANDARD :-',np.std(a))    # How far the values are spread from the mean (average).DISTANCE TAKEN THEN SQUARE THEN ALL ADDED.
print('VARIANCE:-',np.var(a))     # Variance=(Standard Deviation)2
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.percentile(a,90))   # here (a,percentile) is taken.  ptile/100*(len-1)=90/100*(11-1)=0.9*
print(np.argmax(a))          # Index of maximum:-position of maximun value in array.
print(np.argmin(a))          # Index of minimum

MEANS :- 41.81818181818182
MEDIAN :- 30.0
STANDARD :- 29.716289324874825
VARIANCE:- 883.0578512396695
5
95
460
80.0
10
0


In [2]:
# indexing and slicing :-
#slicing means like we xlice mango cut it selective.
import numpy as np

matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix[1:2])

[[4 5 6]]


In [11]:
# 2d indexing:-
import numpy as np
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix[1:3,1:2])    # here matrix[row range,column range] 

[[5]
 [8]]


In [5]:
#boolean indexing:-
arr=np.array([1,2,3,4,5])
print('GREATER THAN 3 :-',arr[arr>3])    # here this arr[arr>3] it is called slicing.

GREATER THAN 3 :- [4 5]


In [4]:
# np.where():-for only indexing
arr=np.array([5,10,15,20,25])
a=np.where(arr>=15)     # always give condition in where means 99%.
print(a)
print(arr[a])

(array([2, 3, 4]),)
[15 20 25]
