In [9]:
# CREATE TWO ARRAY : A=[5,10,15] B=[1,2,3] PERFORM ELEMENT-WISE ADDITION AND MULTIPLICATION:-
import numpy as np

a=[5,10,15]
b=[1,2,3]
print(np.add(a,b))
print(np.multiply(a,b))

[ 6 12 18]
[ 5 20 45]


In [13]:
# GIVEN ARRAY: ARR=[4,8,12,16] EXTRACT ELEMENTS GREATER THAN 10.
import numpy as np

arr=np.array([4,8,12,16,20])
print(arr[arr>10])   # this arr[arr>10]---> this will add the elements to arr but only those which is correct and condition is[arr>10].

[12 16 20]


In [25]:
# CREATE A 2×3 ARRAY OF ONES AND ADD 5 TO EVERY ELEMENT USING BROADCASTING:-
one=np.ones([2,3])
print(one,'\n')
print('AFTER ADDING 5 TO EACH ELEMENT:-'+'\n',np.add(one,5))

[[1. 1. 1.]
 [1. 1. 1.]] 

AFTER ADDING 5 TO EACH ELEMENT:-
 [[6. 6. 6.]
 [6. 6. 6.]]


In [29]:
# GIVEN ARRAY:ARR = [10, 20, 30, 40] COMPUTE: MEAN,SUM,MAXIMUM:-
arr=[10,20,30,40]
print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

25.0
100
40
10


In [39]:
# CONVERT 45 DEGREES INTO RADIANS AND COMPUTE ITS SINE VALUE.:-
import math

a=int(input('ENTER THE DEGREE :-'))
rad=math.radians(a)
print('RADIAN IS :-',rad)
print('ITS SIN VALUE IS :-',math.sin(rad))

ENTER THE DEGREE :- 45


RADIAN IS :- 0.7853981633974483
ITS SIN VALUE IS :- 0.7071067811865476


In [44]:
# CREATE TWO ARRAYS:A = [2, 4, 6, 8] B = [1, 2, 3, 4] PERFORM:FLOOR DIVISION,MODULUS OPERATIONS:-
a=np.array([2,4,6,8])
b=np.array([1,2,3,4])
print('FLOOR DIVISION IS :-',a//b)
print('MODULES ARE :-',a%b)

FLOOR DIVISION IS :- [2 2 2 2]
MODULES ARE :- [0 0 0 0]


In [57]:
# GENERATE A 3×3 RANDOM INTEGER MATRIX BETWEEN 1 AND 20.FIND:STANDARD DEVIATION,VARIANCE:-
mat=np.random.randint(1,21,(3,3))
print(mat)
print('STANDARD DEVIATION :-',np.std(mat))
print('VARIANCE :-',np.var(mat))

[[17 17 11]
 [13 11  5]
 [ 7 14  2]]
STANDARD DEVIATION :- 4.916588197741686
VARIANCE :- 24.17283950617284


In [59]:
# CREATE AN ARRAY FROM 1 TO 9 AND RESHAPE IT INTO 3×3.COMPUTE CUMULATIVE SUM (CUMSUM):-
a=np.arange(1,10)
b=a.reshape(3,3)
print(a)
print(b)
print(np.cumsum(b))  # cumsum means add 1st then 2nd then 3rd like this.1+2+3 like fibonacci series.

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  3  6 10 15 21 28 36 45]


In [69]:
# CREATE ARRAY:ARR = [-3, -1, 0, 1, 3]APPLY:SQUARE,SQUARE ROOT (ONLY VALID VALUES):-
arr=np.array([-3,-1,0,1,3])
print('SQUARE :-',np.square(arr))
print('SQUARE ROOT :-',np.sqrt(arr[arr>=0]))   #TO STORE ONLY THE VALID VALUES.IN ARR.

SQUARE :- [9 1 0 1 9]
SQUARE ROOT :- [0.         1.         1.73205081]


In [80]:
# Create a 3×4 matrix using np.arange().Add 1D array [10, 20, 30, 40] using broadcasting:-
mat=np.arange(0,12).reshape(3,4)
print('MATRIX FORMED :-','\n',mat,'\n')
arr=[10,20,30,40]
res=mat+arr
print('BROADCASTING IS DONE :-','\n',res)

'''broadcasting means :-“Automatically expanding dimensions to make shapes compatible.”
Most of the time broadcasting happens automatically in NumPy.
There is a function called np.broadcast, but it is mainly for advanced/internal use, not normal calculations.'''

MATRIX FORMED :- 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

BROADCASTING IS DONE :- 
 [[10 21 32 43]
 [14 25 36 47]
 [18 29 40 51]]


In [87]:
# Generate 1000 random numbers from normal distribution.Compute:Mean,Standard deviation,95th percentile:-
a=np.random.rand(1,1000)
print(a)
print('MEAN IS :-''\n',np.mean(a))
print('STANDARD DEVIATION MEANS :-',np.std(a))
print('95TH PERCENTILE :-',np.percentile(a,95))

[[3.34183835e-01 1.04698497e-01 4.13818974e-01 5.28478737e-01
  9.90553216e-01 1.77575517e-01 7.80026504e-01 6.01030983e-02
  9.75142934e-01 1.09698069e-01 3.99478215e-01 7.55710584e-01
  5.16639303e-01 3.00932354e-01 5.60462457e-01 1.25620543e-01
  5.27445394e-01 8.70114738e-01 6.10946671e-04 1.58048356e-01
  4.90680095e-01 7.39634836e-01 9.77406554e-01 1.81238977e-01
  9.54310001e-02 8.29630113e-01 4.92446182e-01 3.17428163e-01
  8.86644402e-02 2.30004665e-01 8.06151216e-01 6.19506220e-01
  7.29025635e-02 4.29456530e-01 2.94289533e-01 2.57721860e-01
  2.86713963e-01 9.91260131e-01 4.36171939e-01 7.30154358e-01
  2.52277163e-01 8.17950582e-01 4.06479051e-01 8.56760096e-01
  4.42007277e-01 3.80849339e-01 8.16918194e-01 6.85204940e-01
  3.14926119e-01 9.11228790e-01 4.54566312e-01 2.51086681e-01
  5.71348405e-02 6.42611902e-01 6.77467620e-01 4.47269558e-01
  3.77670527e-01 4.84578344e-01 2.61624811e-01 3.17058063e-01
  1.58671155e-01 7.06871547e-01 2.97577830e-01 8.04490330e-01
  9.8786

In [90]:
#Create two matrices:A (2×3) B (3×2) Transpose A and verify its shape:-
a=np.arange(1,7).reshape(2,3)
print(a)
b=np.arange(1,7).reshape(3,2)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [93]:
# Create array:arr = [1, 2, 3, 4]Compute:Exponential of each element,Natural log,Log base 10:-
arr=[1,2,3,4]
print('EXPONENTIAL:-',np.exp(arr))
print('NATURAL LOG:-',np.log(arr))
print('LOG BASE 10 :-',np.log10(arr))

EXPONENTIAL:- [ 2.71828183  7.3890561  20.08553692 54.59815003]
NATURAL LOG:- [0.         0.69314718 1.09861229 1.38629436]
LOG BASE 10 :- [0.         0.30103    0.47712125 0.60205999]


In [96]:
# Create array:arr = [1.2, 2.5, 3.7, 4.1]Apply:round()floor()ceil()Explain differences based on output:-
arr=[1.2, 2.5, 3.7, 4.1]
print(np.round(arr))    # round means it will decide just by if 3.5 =3 and 3.6=4 like that auto decide.
print(np.floor(arr))   # floor means after point goes to -1 value.
print(np.ceil(arr))    # ceil means after point add+1 to a value.

[1. 2. 4. 4.]
[1. 2. 3. 4.]
[2. 3. 4. 5.]
