In [ ]:
'''NP.UNIQUE---> WORKS AS A SET.
NP.SORT---> USED TO SORT THE LIST.
NP.ARGSORT---> USED TO SORT BUT GIVES OUTPUT IN INDEX.
NP.WHERE
NP.NAN--> MEANS NON-A-NUMBER
NP.ANY--> CHECK EVERY ELEMENT AND IF ONE SATISCFY THEN TRUE.
NP.ALL--> CHECK EVERY ELEMENT AND IF ANY ONE NOT SATISFY THEN FALSE.
NP.CLIP(ARRAY,MIN VALUE,MAX VALUE)---> CHANGES ELEMENT WHEN NOT IN RANGE.
HANDLING NAN VALUES:--
NP.ISINF():-np.isinf() in NumPy checks whether values are infinity (inf or -inf).
-NP.INF():-np.isinf() in NumPy checks whether values are infinity (inf or -inf).

REGEX:-Regex (Regular Expressions) in Python are mainly handled using the built-in re module.
But you can use regex with NumPy string arrays.
Regex means a pattern used to search or match text.

In [2]:
import numpy as np
arr=np.array([90,99,28,386,273,929,2,1929,38,200,283,48,398,29,99,99])
arr2=np.unique(arr)   # np.unique() returns the unique values in sorted order by default.
print(arr2)
print(np.sort(arr))   # ONLY SORT THE ARRAY DO NOT GIVE ONLY UNIQUE
print(np.argsort(arr2))  # np.argsort() returns the index that would sort an array.
print(np.argsort(arr))   # starts from index 0.

[   2   28   29   38   48   90   99  200  273  283  386  398  929 1929]
[   2   28   29   38   48   90   99   99   99  200  273  283  386  398
  929 1929]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 6  2 13  8 11  0 14  1 15  9  4 10  3 12  5  7]


In [4]:
# SET IS DEFINE AS {} IN PYTHON AND IS USED TO GET UNIQUE VALUES.BUT IT DON'T SORT THE VALUES.

a={7,3,28,9,10,28,20}
print(a)

{3, 20, 7, 9, 10, 28}


In [10]:
'''NP.WHERE:- is used to find index where a given condition is true and choose values based on condition.
SYNTAX :---- np.where(condition, value_if_true, value_if_false)'''

import numpy as np

arr = np.array([10, 25, 30, 15])

print(np.where(arr > 20))   # it only provide index of elements when given condition becomes true.
print(arr[arr>20])

(array([1, 2]),)
[25 30]


In [8]:
#NP.NAN:- means “Not a Number” in NumPy.It is used to represent missing, undefined, or invalid numeric values.

arr=np.array([10, 20, np.nan, 40, 50, np.nan])
print(np.nanmean(arr))    # nanmean will ignore nan values.
a=np.where(np.isnan(arr),0,arr)   #nan is never equal to anyone not even itself so never where in condition arr==np.nan use this np.isnan(arr)
print(a)
print(np.mean(a))

30.0
[10. 20.  0. 40. 50.  0.]
20.0


In [13]:
#np.any:- checks if at least one value is True in an array.
arr = np.array([0, 0, 5])
arr2=np.array([0,0,0])
arr3=np.array([1,2,3,4,5,6])
print(np.any(arr))
print(np.any(arr2))
print(np.any(arr3))

True
False
True


In [14]:
# np.all:- COMPULSORY ALL VALUE SHOULD BE TRUE IN AN ARRAY.
arr = np.array([0, 0, 5])
arr2=np.array([0,0,0])
arr3=np.array([1,2,3,4,5,6])
print(np.all(arr))
print(np.all(arr2))
print(np.all(arr3))

False
False
True


In [15]:
# np.clip:- is used to limit values within a minimum and maximum range.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(np.clip(arr,5,10))   # CHANGES ELEMENT WHEN NOT IN RANGE.

[ 5  5  5  5  5  6  7  8  9 10 10 10 10 10 10]


In [2]:
# HOW TO HANDLE NAN VALLUES :-

# first to detect nan values:-
import numpy as np

arr = np.array([10, np.nan, 30])

print('BOOLEAN VALUES TO FIND NAN PLACES:-',np.isnan(arr))


# REMOVE NAN VALUES:-
arr2=np.array([10,np.nan,30])
clean=arr2[~np.isnan(arr2)]   # here ~ is symbol for not means not np.isnan(arr2) then store the values to arr2.
print('REMOVED NAN:-',clean)


# REPLACE NAN VALUES:-
arr3=np.array([10,np.nan,30])
arr3[np.isnan(arr3)]=0      #  ASSIGNED 0 TO NAN VALUES.
print('REPLACED NAN :-',arr3)


#Ignore NaN in calculations
arr4=np.array([10,np.nan,30])
print('IGNORING NAN VALUES IN CALCULATIONS:-',np.nanmean(arr4))

'''
nan-mean
nan-max
nan-sum
nan-min
nan-std
nan-var
nan-median
nan-percentile
nan-argmax
nan-argmin

this all can be used for ignoring nan values and doing regular calculations.'''

BOOLEAN VALUES TO FIND NAN PLACES:- [False  True False]
REMOVED NAN:- [10. 30.]
REPLACED NAN :- [10.  0. 30.]
IGNORING NAN VALUES IN CALCULATIONS:- 20.0


'\nnan-mean\nnan-max\nnan-sum\nnan-min\nnan-std\nnan-var\nnan-median\nnan-percentile\nnan-argmax\nnan-argmin\n\nthis all can be used for ignoring nan values and doing regular calculations.'

In [5]:
#NP.INF ,-NP.INF:-

import numpy as np

arr = np.array([10, np.inf, -np.inf, 25])

print(np.isinf(arr))
print(arr[~np.isinf(arr)])  # to print only true values.

[False  True  True False]
[10. 25.]


In [7]:
# REGEX:-
import re

a='apple.iphone'
reslt=re.findall('p',a)
print(reslt)

['p', 'p', 'p']


In [8]:
# REGEX:-
import re

text = "apple123"

result = re.findall(r'\d+', text)   # \d → digit,,,+ → one or more digits,,,so \d+ means “find all numbers in given array”

print(result)

['123']


In [17]:
# REGEX:-
import numpy as np
import re

arr = np.array(["cat1", "dog", "lion22", "tiger"])

for i in arr:
    if re.search(r'\d', i):  # \d means find digit in given array.This checks which strings contain digits.
        print('1st:- ',i)
for i in arr:
    if re.search(r'^t',i):  # r'^t' means search elements with first letter t.
        print('2nd:- ',i)
for i in arr:
    if re.search(r'\d+$',i):  # return element with more than one digits at last.
        print('3rd:-  ',i)

1st:-  cat1
1st:-  lion22
2nd:-  tiger
3rd:-   cat1
3rd:-   lion22
