In [1]:
'''Create a Python list to represent a playlist of 5 song durations in seconds (e.g., [210, 180, 245, 200, 175]).
Print the total duration of the playlist.'''

lst=[210, 180, 245, 200, 175]
print(sum(lst))

1010


In [16]:
'''Represent a 3x3 matrix in Python to store the ratings (1-5) given by 3 friends to 3 different food items on Swiggy. 
Print the matrix and display the rating each friend gave to the second food item.'''
import numpy as np

matrix=np.random.randint(0,6,(3,3))
print(matrix)
print('SECOND FOOD ITEM RATING :- ',matrix[:,1])

[[3 1 3]
 [2 4 4]
 [0 3 2]]
SECOND FOOD ITEM RATING :-  [1 4 3]


In [21]:
'''Given a matrix representing the number of orders for 4 different dishes across 3 days (rows: days, columns: dishes), 
write code to calculate and print the total orders for each dish.'''

orders = np.random.randint(20,50,(4,4))
print(orders)
print('SUM OF ALL THE PERTICULAR ORDERS ARE :--',np.sum(orders,axis=0))


[[22 24 29 46]
 [31 22 21 32]
 [34 48 40 35]
 [37 26 22 47]]
SUM OF ALL THE PERTICULAR ORDERS ARE :-- [124 120 112 160]


In [54]:
'''Imagine you have a table of 5 Flipkart products with columns for price and quantity sold. 
Represent this data as a matrix in Python, then write a function to calculate the total revenue for each product.
<br><br><em><strong>Hint:</strong> Multiply price and quantity for each row, then print the results.</em>'''

product=np.random.randint(1,6,5)
prize=np.random.randint(2000,100000,5)
sold=np.random.randint(20,50,5)

matrix=np.column_stack((product,sold,prize))

def total_rev(data):
    return data[:,1]*data[:,2]
    
print(f'PRODUCT CODE IS :-{product}\n\nPRIZE OF THE PRODUCT IS \n{prize}\n\n QUANTITY OF PRODUCT SOLD :-\n{sold}')
print('TOTAL REVENUE IS :-\n',total_rev(matrix))

PRODUCT CODE IS :-[4 2 5 2 2]

PRIZE OF THE PRODUCT IS 
[15468 19252 77805 10520  2058]

 QUANTITY OF PRODUCT SOLD :-
[26 22 42 42 23]
TOTAL REVENUE IS :-
 [ 402168  423544 3267810  441840   47334]
