In [9]:
'''Given two 2x2 matrices representing the number of likes and comments on two Instagram posts over two days, 
write Python code to multiply them and display the resulting matrix.'''
import numpy as np

like=np.random.randint(200,50000,(2,2))
comment=np.random.randint(200,50000,(2,2))

print(f'LIKES :- \n\n{like}\n\nCOMMENTS :-\n\n{comment}')
print('\nRESULT OF THEIR MULTIPLY IS :-\n',np.multiply(like,comment))

LIKES :- 

[[ 3717 17313]
 [30708 22766]]

COMMENTS :-

[[21200 24174]
 [49883 12833]]

RESULT OF THEIR MULTIPLY IS :-
 [[  78800400  418524462]
 [1531807164  292156078]]


In [10]:
'''Create a simple Python function linear_regression_predict(x, m, c) that takes an input value x, slope m, and intercept c, and 
returns the predicted output y for a linear regression equation y = mx + c.'''

def linear_regression_predict(x, m, c):
    y = m * x + c
    return y

prediction = linear_regression_predict(6, 10, 20)

print(prediction)

80


In [17]:
'''Imagine you are predicting the delivery time for Zomato orders based on distance. Given three distances (2km, 5km, 8km) and 
a linear regression equation y = 4x + 10 (where y is minutes), use your function from the previous task to calculate the predicted delivery time 
for each distance.'''

distance=[2,5,8]
for i in distance:
    print(f'FOR DISTANCE {i} KM THE DELIVERY TIME IS :--{linear_regression_predict(i,4,10)} MIN')

FOR DISTANCE 2 KM THE DELIVERY TIME IS :--18 MIN
FOR DISTANCE 5 KM THE DELIVERY TIME IS :--30 MIN
FOR DISTANCE 8 KM THE DELIVERY TIME IS :--42 MIN


In [ ]:
'''Explain in your own words what the slope and intercept represent in the context of Flipkart's product price prediction 
(e.g., predicting price based on product rating). Write 2-3 sentences for each term.'''

'''
The slope represents how much the predicted product price changes when the product rating increases by 1 point.
For example, if the slope is ₹500, then for every 1-star increase in rating, the predicted price increases by ₹500.

The intercept is the predicted product price when the product rating is 0. 
Although a 0-star rating may not be realistic on Flipkart, 
the intercept serves as the starting value from which the regression line makes its predictions.'''


In [ ]:
'''Use ChatGPT to ask: 'How does matrix multiplication help in training a machine learning model like Spotify's song recommendation system?' 
Summarize the answer in your own words in 3-4 sentences.'''

'''In Spotify's song recommendation system, user preferences and song features are stored as matrices, and multiplying these matrices helps the model find similarities between users and songs.
This allows the system to predict which songs a user is most likely to enjoy and recommend them accurately.'''
