In [ ]:
'''WHAT IS VECTOR ?
-A vector is an ordered list of numbers that has magnitude (size) and direction.

Example:-

v = [2, 5]

This vector has two values:

x = 2
y = 5

-It represents a point or movement from the origin (0,0) to (2,5).'''

In [ ]:
'''ROW VECTOR:--
[2 5 8]

COLUMN VECTOR :--
[[2]
 [5]
 [8]]

* numpy is 3d so after that vector we have to use for 20d like that.
Dimension of Vector:--
Number of elements.

[5,2]      → 2D

[4,7,1]    → 3D

[1,2,3,4]  → 4D

General rule:--

If a vector contains n elements, then it is an n-dimensional vector.

DIMENSION OF A VECTOR = NUMBER OF ELEMENTS IN IT.

So, in statistics, vectors can be 1D, 2D, 3D, 10D, 100D, 1000D, or even millions of dimensions, depending on how many variables or 
features you are working with. There is no theoretical maximum.'''

In [ ]:
'''example:--

Each dimension usually represents one feature (variable).

For example, suppose a student has:

Age = 20
Height = 170 cm
Weight = 65 kg
Marks = 88
Attendance = 95%

The student's data can be written as the vector:

[20,170,65,88,95]

This is a 5-dimensional (5D) vector because it has 5 values.

In [ ]:
'''Real-life Examples:-

-GPS location
-Speed of a car
-Wind direction
-Player movement in games
-Image pixels
-Machine learning features'''

In [ ]:
'''WHAT IS MATRIX ?
-A matrix is a rectangular arrangement of numbers in rows and columns.

EXAMPLE:-
A =[[1 2]
    [3 4]]

here row = 2 , column = 2 , shape= 2 x 2

ANOTHER EXAMPLE:--
B =[[5 6 7]
    [1 2 3]]

HERE ROWS = 2 , COLUMN = 3 SO, SHAPE = 2 X 3'''

In [ ]:
'''Difference Between Vector and Matrix:---

| Vector                    | Matrix                               |
| ------------------------- | ------------------------------------ |
| Single list of numbers    | Grid of numbers                      |
| Has one row or one column | Has multiple rows and columns        |
| Represents direction/data | Represents transformation or dataset |
| Example: `[2,5]`          | Example: `[[1,2],[3,4]]`             |
'''

In [ ]:
'''Identity Matrix:--
Diagonal = 1
Others = 0

[[1 0 0]
 [0 1 0]
 [0 0 1]]

 in python :-- np.eye(3)
----------------------------------------------------------------
Zero Matrix:--
Everything is zero.

[[0 0]
 [0 0]]

in python :- np.zeros((2,2))'''

In [ ]:
'''Basic Matrix Operations:--

Rule:

✅ Both matrices must have the same dimensions.
------------------------------------------------------------
ADDITION :-

A =[[1 2]
    [3 4]]

B =[[5 6]
    [7 8]]

A+B=[[6 8]
    [10 12]]    LIKE THIS ALSO SUBSTRACTION.
-------------------------------------------------------------
MULTIPLICATION:--
A * B=[[5 12]
      [21 32]]

IN PYTHON:--A @ B or np.dot(A,B) BOTH TRUE BOTH DO MULTI OF A AND B.'''

In [ ]:
'''Transpose:--
Rows become columns.

EXAMPLE:-

A
[[1 2]
 [3 4]]

Transpose of A
[[1 3]
 [2 4]]
'''