In [ ]:
'''MANUAL ITERATION(ELEMENT BY EMLEMENT PROCESSING)
-IF WE WANT TO APPLY A LIST +2 THEN A LOOP IS USED.
BUT IF LIST HAS 1000 ELEMENT THEN IT TAKE TIME.IN STATIC

VECTORIZATION:-IN 1 SEC IT APPLIES TO ALL.

In [ ]:
'''LIST:- 1D AND 2D AND 3D.
NUMPY IS ALSO A ARRAY STRUCTURE.
IT REMOVES , THAT WE PUT IN LIST.
IT APPLIES THE CONDITION ALL OF THEM AT ONE TIME.

1D:- JUST LIKE OUR SIMPLE LIST.IT IS TYPE OF LINE.
EX:-[10,20,30]

2D LIST MEANS :- IT IS TYPE OF TABLE(ROW AND COLUMN)
LIST IN A LIST.
EX:-a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

3D:-A 3D LIST IS LIKE MULTIPLE 2D TABLES TOGETHER(COLLECTION OF TABLE).
EX:-a = [
    [
        [1, 2],
        [3, 4]
    ],

    [
        [5, 6],
        [7, 8]
    ]
]
'''

In [3]:
import numpy as np
# 1D LIST:-
marks = [80, 75, 90, 60]

# ONLY SUPPORT IN NUMPY:-
# 2D LIST:- TABLE(ROW AND COLUMN)(MATRIX FORM-ROW AND COLUMN)
students = np.array([
    ["Ram", 80],
    ["Shyam", 75],
    ["Mohan", 90]
])

# 3D LIST(COLLECTION OF TABLES):-
hospital = np.array([
    [   # Floor 1
        ["Room1", "Room2"],
        ["Room3", "Room4"]
    ],

    [   # Floor 2
        ["Room5", "Room6"],
        ["Room7", "Room8"]
    ],
    [   # Floor 3
        ["Room9", "Room10"],
        ["Room11", "Room12"]
    ]
])
print('number of dimensions',hospital.ndim)
print('size',hospital.size)
print('shape',hospital.shape)
print('type',hospital.dtype)   # not more than one supported type at a time.

number of dimensions 3
size 12
shape (3, 2, 2)
type <U6


In [29]:
hospital = np.array([
        'room1','room2','room3','room4','room5','room6'
])
a=hospital.reshape(3,2,1)
print(a)

'''
Shape (3,2,1) means:

3 blocks
each block has 2 rows
each row has 1 element

RULE:--3 x 2 x 1 = 6 (ALWAYS MULTIPLY)'''

[[['room1']
  ['room2']]

 [['room3']
  ['room4']]

 [['room5']
  ['room6']]]


In [ ]:
'''MATRIX ADDITION:-
[1 2 3] + [0 0 0] = [1 2 3]   THIS IS CORRECT MEANS ADDITION IS PROPER.
[1 2 3] * [0 0 0] = [0 0 0]  THIS IS WHEN WE WANT 0 IN OUTPUT

[1 1 1] [1 1 1] * 3.14 = [3.14 3.14 3.14] [3.14 3.14 3.14]

In [34]:
one_array=np.ones((2,3))
print('ones array :-')
print(one_array,'\n')

zeros_array=np.zeros((2,3))
print('zeros array :-')
print(zeros_array,'\n')

range_array=np.arange(1,10,2)    #start,stop,step,dtype=type.
print('range array :-')
print(range_array,'\n')

range_array2=np.arange(1,101)
b=range_array2.reshape(10,10)
print(b)

ones array :-
[[1. 1. 1.]
 [1. 1. 1.]] 

zeros array :-
[[0. 0. 0.]
 [0. 0. 0.]] 

range array :-
[1 3 5 7 9] 

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
'''NumPy in Simple Words

NumPy is a Python library used for:

-fast calculations
-working with arrays
-maths operations on many numbers together'''

In [ ]:
'''So NumPy changes the meaning of operators like:

+
-
*
/

to work mathematically on all elements.'''

In [2]:
# NORMAL LIST WITHOUT NUMPY():-
a = [1,2,3]

new = []

for i in a:
    new.append(i + 2)

print(new)

[3, 4, 5]


In [3]:
# USING WITH NUMPY():-
import numpy as np
a=np.array([1,2,3,4,5])
print(a+2)

#NumPy automatically adds 2 to all elements.FASTER AND EASIER.
# ADDS TO EVERY ELEMENT ITSELF JUST BY PRINT(A+2).
# Because NumPy array is built for mathematics.
#LIST WILL NOT DO SO BECAUSE IN LIST + MEANS ADD LIST.
# ONLY USE ONE DATA-TYPE AT A TIME.NO MIXING UP.
#STRING AND BOOLEAN NEVER USED.

[3 4 5 6 7]


In [17]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])

print('add :-',arr1+arr2)
print('sub :-',arr1-arr2)
print('multi :-',arr1*arr2)
print('div :-',arr1/arr2)


# NOTE ONLT SAME MATRIX IS POSSIBLE MEANS [5 ELEMENTS] + [MUST BE 5 ELEMETS].

add :- [ 5  7  9 11 13]
sub :- [-3 -3 -3 -3 -3]
multi :- [ 4 10 18 28 40]
div :- [0.25       0.4        0.5        0.57142857 0.625     ]


In [5]:
# DOING SAME WITH NORMAL LIST:-
a=[1,2,3]
#print(a+2)         # this will give error.
print(a+[4,5])     # here + means combine list.

[1, 2, 3, 4, 5]


In [31]:
'''
np.linspace:-(1,10,5)
USED TO CREATE A LINSPACE BETWEEN TWO NUMBERS
ALSO THE DIFFERENCE BETWEEN THE ELEMENTS BETWEEN THEM REMAIN CONSTANT.
'''

'\nnp.linspace:-(1,10,5)\nUSED TO CREATE A LINSPACE BETWEEN TWO NUMBERS\nALSO THE DIFFERENCE BETWEEN THEM REMAIN CONSTANT.\n'

In [24]:
# NP.LINSPACE:-

arr=np.linspace(1,20,5)
print(arr)

# it will have equal distance for output.

[ 1.    5.75 10.5  15.25 20.  ]


In [ ]:
'''NP.EMPTY:-
THIS IS USED FOR CREATING ARRAY WITHOUT ASSIGNING ANY VALUES TO IT .
IT IS FASTER THAN ZEROS AND ONES ,, BECAUSE VALUES ARE NOT ASSIGNED.
IT IS USED WHEN TAKING RANDOMS AND VALUES ARE OVERWRITTEN.
'''

In [35]:
arr=np.empty((3,3))
print(arr)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


In [7]:
print(np.identity(4))  # square is compulsory number of row and column same always.
print(np.eye(3,4))    # this is for rectangle.uneven row and column.the identity will be taken as per biggest value only.
print(np.eye(4,3))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
'''np.random.rand()--> for uniform distribution values lie between (0,1)
()---> shape
np.random.randn()---> n for negative numbers.
np.random.randint()----> for integers.
np.random.choice()----> you have to give choice ut will select from it.

In [16]:
print(np.random.rand(2,2))
print(np.random.randn(2,2))
print(np.random.randint(2,10,(2,3)))
print(np.random.choice([10,20,30],size=9))
print(np.random.seed(42))  
#if random has 9th value changing always and 8th is depend on 9th.
#then due to that 8th do not change so we use seed.

[[0.33783325 0.86701236]
 [0.43176464 0.20899525]]
[[ 0.79881671  1.05813398]
 [ 1.91043013 -0.11339141]]
[[6 6 4]
 [3 2 6]]
[30 30 10 30 10 10 30 30 10]
None


In [ ]:
'''np.transpose:-
it is used to convert row to column and column to row.

In [ ]:
# USING OF TRANSPOSE:-

arr=np.arange(1,17)
print(arr)
mat=arr
b=mat.reshape(4,4)         
print(b)
print(np.transpose(b))   # USED TO CONVERT ROW TO COLUMN AND COLUMN TO ROW.

In [ ]:
'''reshape():- original array will not be disturbed
resize():- original array will be disturbed
ravel(view)  and flatten(copy)'''

In [5]:
# REVAL AND FLATTEN USE:-

# CREATE AN ARRAY OF 1 TO 9 AND FLATTEN IT USING RAVEL(),FLATEN IT USING FLATEN():-

arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
mat=arr.reshape(3,3)
print(mat)
print(mat.ravel())   # usually returns a view (linked to original array)
print(mat.flatten())  # returns a copy (separate array)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
'''logspace() means: 👉 "Create numbers whose powers increase equally."
Normal numbers increase like:
10,20,30
BUT IN LOGSPACE() INCRESE BY MULTIPLICATION:-
10,100,1000
BECAUSE POWER ARE CHANGING.

-->by default np.logspace() uses base 10.

In [3]:
# LOGSPACE:-
import numpy as np
arr=np.logspace(1,5,5,base=2)    # (start, stop, total_numbers, base)
print(arr)

#here it is 2 raise^ to 1 then 2^2 then 2^3 till 2^5 and total numbers are 5. by default base is 10 in numpy.

[ 2.  4.  8. 16. 32.]


In [4]:
#CREATE A RANDOM INTEGER MATRIX WITH OF SHAPE 3X3 WITH VALUES BETWEEN 10 AND 50:-

arr=np.random.randint(10,50,9)  # by default randint creates only 1 random number but ,9 means 9 random numbers are created.
b=arr
c=b.reshape(3,3)
print(c)

[[28 24 36]
 [34 29 40]
 [28 40 20]]
