In [27]:
'''Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato.
Use slicing to extract the ratings given by the second and third users only.'''
import numpy as np

a=np.array(['VEG PULAV','BIRYANI','MAGGIE','NOODLES','PIZZA'])
ratings = np.array([
    [4, 5, 3, 4, 5],   # User 1
    [3, 4, 5, 2, 4],   # User 2
    [5, 5, 4, 3, 5],   # User 3
    [2, 3, 4, 5, 3]    # User 4
])
print(f'FOOD ITEMS :-- {a}')
b=['1st','2nd','3rd','4th']
for i,h in zip(ratings,b):
    print(f'RATING BY {h} USER:-- {i}')
selected_user=ratings[1:3]
print('\n SELECTED RATING OF USER 2ND AND 3RD :--\n',selected_user)

FOOD ITEMS :-- ['VEG PULAV' 'BIRYANI' 'MAGGIE' 'NOODLES' 'PIZZA']
RATING BY 1st USER:-- [4 5 3 4 5]
RATING BY 2nd USER:-- [3 4 5 2 4]
RATING BY 3rd USER:-- [5 5 4 3 5]
RATING BY 4th USER:-- [2 3 4 5 3]

 SELECTED RATING OF USER 2ND AND 3RD :--
 [[3 4 5 2 4]
 [5 5 4 3 5]]


In [34]:
'''Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong>
Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>'''

steps=np.random.randint(6000,11000,10)
print(steps)
a=(steps>8000)
print(a)
b=steps[steps>8000]
print(b)

[10661 10473 10193  7444  9584  8530  6591  7166  7545  7446]
[ True  True  True False  True  True False False False False]
[10661 10473 10193  9584  8530]


In [39]:
'''Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.'''
match=np.array([774,816,676,877,728,658,625,866])
print(match)
print(match[1],match[4],match[6])

[774 816 676 877 728 658 625 866]
816 728 625


In [43]:
'''Suppose you have a NumPy array of product prices from Flipkart.
Use broadcasting to apply a 10% discount to all prices and print the new array.<br><br><em><strong>Constraint:</strong>
Do not use any loops.</em>'''

prices=np.array([100,2000,1300,12000,1900,990,2500,9000])
print(prices)
discount=prices*10/100
ori_prices=prices-discount
print(ori_prices)

[  100  2000  1300 12000  1900   990  2500  9000]
[   90.  1800.  1170. 10800.  1710.   891.  2250.  8100.]


In [50]:
'''Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify,
use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.'''

user_rat=np.array([-1 ,2 ,2, 2,-3,-5,-4 ,0 ,1 ,0])
print(user_rat)
user_rat[user_rat<0]=0
print(user_rat)

[-1  2  2  2 -3 -5 -4  0  1  0]
[0 2 2 2 0 0 0 0 1 0]
