In [7]:
'''Install NumPy in your Python environment using pip, then create a Python file called insta_likes.py and import numpy as np at the top.
Create a NumPy array called followers using np.array() that stores the follower counts for 5 Instagram influencers: [1200, 15000, 67000, 340000, 1250000].
Print the array, its shape, number of dimensions, and data type.'''
import numpy as np

followers=np.array([1200,15000,67000,340000,1250000])
print(followers)
print(np.shape(followers))
print(followers.ndim)
print(followers.dtype)

[   1200   15000   67000  340000 1250000]
(5,)
1
int64


In [13]:
'''Use np.arange() to generate an array of order IDs for 10 consecutive Zomato orders starting from 101. Print the array and its size.'''
a=np.arange(101,111,1)   # here it is np.arange(start,stop,step)
print(a)
print(np.size(a))

[101 102 103 104 105 106 107 108 109 110]
10


In [14]:
'''Create a 3x3 NumPy array using np.eye() to represent a 'like' identity matrix for a new Spotify playlist feature.
Print the matrix and explain what the diagonal values represent in a comment.'''

print(np.eye(3,3))

# The diagonal values (1s) represent that each playlist item
# matches or identifies with itself. The 0s represent no match
# between different items.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
'''Convert a Python list of cricket scores [45, 67, 120, 89, 54] to a NumPy array,
then use the .itemsize attribute to print how many bytes each score takes in memory.<br><br><em><strong>Hint:</strong>
Use np.array() for conversion and .itemsize for memory size.</em>'''
a=[45, 67, 120, 89, 54]
lst=np.array(a)
print(lst)
print(np.dtype(np.int64).itemsize)

[ 45  67 120  89  54]
8
