In [4]:
'''Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition,
subtraction, multiplication, and division to compare their activity levels.'''
import numpy as np

a=np.array([959,1103,1006,1039,928,1062,1054])
b=np.array([1048,918,1125,961,1085,1119,1012])
print(f'{a+b}\n{a-b}\n{a*b}\n{a/b}')

[2007 2021 2131 2000 2013 2181 2066]
[ -89  185 -119   78 -157  -57   42]
[1005032 1012554 1131750  998479 1006880 1188378 1066648]
[0.91507634 1.20152505 0.89422222 1.08116545 0.85529954 0.94906166
 1.04150198]


In [6]:
'''Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity),
use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.'''
user_song=np.array([
    [5,4,2],
    [3,4,1],
    [2,2,5]])

song_pop=np.array([
    [3,2,5],
    [4,3,1],
    [4,4,5]])

dot=np.dot(user_song,song_pop)
print(dot)
matmul=np.matmul(user_song,song_pop)
print(matmul)

# FOR 2-D ARRAY THERE IS NO DIFFERENCE BETWEEN DOT AND MATMUL.Both perform standard matrix multiplication and produce the same result.

[[39 30 39]
 [29 22 24]
 [34 30 37]]
[[39 30 39]
 [29 22 24]
 [34 30 37]]


In [12]:
'''Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and
then calculate the mean, median, standard deviation, and variance of the pixel values.'''

ins_img=np.array([
    [4,3,2,1],
    [4,5,6,7],
    [5,6,7,8],
    [8,9,9,1]])
trans=np.transpose(ins_img)
print(trans)
print('MEAN:--\n',np.mean(trans))
print('MEDIAN:--\n',np.median(trans))
print('STD:--\n',np.std(trans))
print('VARIANCE:--\n',np.var(trans))

[[4 4 5 8]
 [3 5 6 9]
 [2 6 7 9]
 [1 7 8 1]]
MEAN:--
 5.3125
MEDIAN:--
 5.5
STD:--
 2.567069097239106
VARIANCE:--
 6.58984375


In [14]:
'''Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and
use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong>
If the matrix is not invertible, modify one value and try again.</em>'''

rat=np.array([
    [2,3,5],
    [4,3,1],
    [5,5,4]])

deter=np.linalg.det(rat)          # np.linalg stands for NumPy Linear Algebra.
print(deter)

inv=np.linalg.inv(rat)
print(inv)

eig=np.linalg.eig(rat)
print(eig)

'''
| Function          | Purpose                                                 |
| ----------------- | ------------------------------------------------------- |
| `np.linalg.det()` | Calculates the determinant of the matrix                |
| `np.linalg.inv()` | Calculates the inverse matrix (only if determinant ≠ 0) |
| `np.linalg.eig()` | Returns eigenvalues and eigenvectors                    |
'''

5.999999999999998
[[ 1.16666667  2.16666667 -2.        ]
 [-1.83333333 -2.83333333  3.        ]
 [ 0.83333333  0.83333333 -1.        ]]
EigResult(eigenvalues=array([10.56776436, -1.        , -0.56776436]), eigenvectors=array([[ 5.62245851e-01,  7.07106781e-01,  6.43264487e-01],
       [ 3.93304857e-01, -7.07106781e-01, -7.55689250e-01],
       [ 7.27455079e-01, -8.26704618e-17,  1.23063224e-01]]))


In [23]:
'''Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days.
Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.'''

citys=np.array([
    [1,2,3,4,5,6],
    [6,5,4,3,2,1]])
a=citys.reshape(3,4)
print(a)
flt=citys.flatten()
print(flt)
part1,part2=np.split(citys,2)
print(f'\npart1:-{part1}\npart2:-{part2}')
stk=np.vstack((part1,part2))
print(stk)

[[1 2 3 4]
 [5 6 6 5]
 [4 3 2 1]]
[1 2 3 4 5 6 6 5 4 3 2 1]

part1:-[[1 2 3 4 5 6]]
part2:-[[6 5 4 3 2 1]]
[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]
